### ISSUE TITLE
Shortcodes plugin causing issues on pages without an URL

### ISSUE THREAD

**Issue by ChristopherDosin** [Shape-and-Shift/SasShortcode#8]
We have found a compatibility issue with the Shortcodes plugin and plugins that contains html forms (ex. ). 

When we submit a form with a post request, this will load a new page and will trigger ResponseSubscriber where an error is returned (see image below). This error is produced by the subscriber ResponseSubscriber at sas/shortcode/src/Subscriber/ResponseSubscriber.php because the $host returns null when the page is loaded by a form.Back in stock notifications. 

![image](https://user-images.githubusercontent.com/8193345/146894384-3d45bebd-9289-49d4-b7bf-fe99fd246d15.png)

**Comment by LarsPauwels** [comment]
If any questions, please ask.

**Comment by pedramham** [comment]
> If any questions, please ask.

Hi @LarsPauwels  . I created a simple form plugin to simulate this bug.But i could not make this error.Can you help me how to create this bug.

https://github.com/pedramham/testFormPlugin

**Comment by LarsPauwels** [comment]
We had a problem with the combination of the shortcode plugin and the back in stock plugin (https://store.shopware.com/en/zeobv82482397379/back-in-stock-notifications-plugin-of-the-month.html). If I compare your test with the plugin setup then I found out that the submit endpoint contains the store-api scope instead of the storefront scope. 
![image](https://user-images.githubusercontent.com/43349729/147742481-69f5c18e-1ebb-4b36-bf5f-21dc29039965.png)

**Comment by LarsPauwels** [comment]
So I think you need to change the scope in the file src/Controller/SubmitFormController.php.

**Comment by ChristopherDosin** [comment]
@LarsPauwels So in this case it should be fixed within the `GetNotified` plugin you use, right?

**Comment by LarsPauwels** [comment]
As far as I can see this would fix it.

**Comment by ChristopherDosin** [comment]
Okay, then i will close this issue. If there're any problems feel free to create a new one or re-open it.

**Comment by LarsPauwels** [comment]
Super. I will test this right now.

**Comment by LarsPauwels** [comment]
I looked at it and there are multiple plugins using this way. So I can't change alle the plugins that use a different scope. The problem is that if a different scope is used the host null is. So In the shortcode plugin needs to be a check of some sort the prevent this error.
